# Generated by Django 4.2 on 2024-10-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
