# Generated by Django 4.2 on 2024-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfol", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="porfol/images/"),
        ),
    ]
